#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FlashCardsPort.Droid.Resource", IsApplication=true)]

namespace FlashCardsPort.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.InAppBilling.Resource.String.library_name = global::FlashCardsPort.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layout_constraintBaseline_creator = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int layout_constraintBaseline_toBaselineOf = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int layout_constraintBottom_creator = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int layout_constraintBottom_toBottomOf = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int layout_constraintBottom_toTopOf = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int layout_constraintDimensionRatio = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int layout_constraintEnd_toEndOf = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int layout_constraintEnd_toStartOf = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int layout_constraintGuide_begin = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int layout_constraintGuide_end = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int layout_constraintGuide_percent = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int layout_constraintHorizontal_bias = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int layout_constraintHorizontal_chainPacked = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int layout_constraintHorizontal_weight = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int layout_constraintLeft_creator = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int layout_constraintLeft_toLeftOf = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int layout_constraintLeft_toRightOf = 2130771984;
			
			// aapt resource value: 0x7f010011
			public const int layout_constraintRight_creator = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int layout_constraintRight_toLeftOf = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int layout_constraintRight_toRightOf = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int layout_constraintStart_toEndOf = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int layout_constraintStart_toStartOf = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int layout_constraintTop_creator = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int layout_constraintTop_toBottomOf = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int layout_constraintTop_toTopOf = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int layout_constraintVertical_bias = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int layout_constraintVertical_chainPacked = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int layout_constraintVertical_weight = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int layout_editor_absoluteX = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int layout_editor_absoluteY = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int layout_goneMarginBottom = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int layout_goneMarginEnd = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int layout_goneMarginLeft = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int layout_goneMarginRight = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int layout_goneMarginStart = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int layout_goneMarginTop = 2130772003;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int theme_background = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int theme_devicedefault_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cross = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_south = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Picture = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int tick = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int Camera = 2131230724;
			
			// aapt resource value: 0x7f08001b
			public const int Cancel = 2131230747;
			
			// aapt resource value: 0x7f080008
			public const int Cancel_create_card = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int Card_1 = 2131230721;
			
			// aapt resource value: 0x7f08001a
			public const int Cost_deck = 2131230746;
			
			// aapt resource value: 0x7f080018
			public const int Deck = 2131230744;
			
			// aapt resource value: 0x7f080005
			public const int Galery = 2131230725;
			
			// aapt resource value: 0x7f08001c
			public const int Ok = 2131230748;
			
			// aapt resource value: 0x7f080009
			public const int Save_create_card = 2131230729;
			
			// aapt resource value: 0x7f08004b
			public const int TeachingDecksListView = 2131230795;
			
			// aapt resource value: 0x7f08000d
			public const int acrhive_deck_list_view = 2131230733;
			
			// aapt resource value: 0x7f080030
			public const int activity_dash_board = 2131230768;
			
			// aapt resource value: 0x7f080028
			public const int activity_main = 2131230760;
			
			// aapt resource value: 0x7f080020
			public const int activity_sign_up = 2131230752;
			
			// aapt resource value: 0x7f08003a
			public const int add = 2131230778;
			
			// aapt resource value: 0x7f08000a
			public const int archiveCardListView = 2131230730;
			
			// aapt resource value: 0x7f080037
			public const int archive_button = 2131230775;
			
			// aapt resource value: 0x7f080039
			public const int button5 = 2131230777;
			
			// aapt resource value: 0x7f080002
			public const int card_icon = 2131230722;
			
			// aapt resource value: 0x7f080010
			public const int code = 2131230736;
			
			// aapt resource value: 0x7f080012
			public const int code_false = 2131230738;
			
			// aapt resource value: 0x7f08003d
			public const int countRepeatButton = 2131230781;
			
			// aapt resource value: 0x7f080032
			public const int dashboard_btn_edit = 2131230770;
			
			// aapt resource value: 0x7f080033
			public const int dashboard_btn_exit = 2131230771;
			
			// aapt resource value: 0x7f080031
			public const int dashboard_welcome = 2131230769;
			
			// aapt resource value: 0x7f080035
			public const int decks = 2131230773;
			
			// aapt resource value: 0x7f08001f
			public const int delete_item = 2131230751;
			
			// aapt resource value: 0x7f08004d
			public const int done = 2131230797;
			
			// aapt resource value: 0x7f08001e
			public const int edit_item = 2131230750;
			
			// aapt resource value: 0x7f080027
			public const int forgot_btn_login = 2131230759;
			
			// aapt resource value: 0x7f080024
			public const int forgot_btn_reset = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int forgot_btn_signup = 2131230757;
			
			// aapt resource value: 0x7f080023
			public const int forgot_email = 2131230755;
			
			// aapt resource value: 0x7f080022
			public const int forgot_input_email = 2131230754;
			
			// aapt resource value: 0x7f080026
			public const int forgot_layout_or = 2131230758;
			
			// aapt resource value: 0x7f080021
			public const int icon = 2131230753;
			
			// aapt resource value: 0x7f080003
			public const int icon_card = 2131230723;
			
			// aapt resource value: 0x7f080013
			public const int imageView = 2131230739;
			
			// aapt resource value: 0x7f08004c
			public const int item1 = 2131230796;
			
			// aapt resource value: 0x7f080016
			public const int list = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int list_card = 2131230743;
			
			// aapt resource value: 0x7f08000e
			public const int list_cards = 2131230734;
			
			// aapt resource value: 0x7f08002c
			public const int login_btn_forgot_password = 2131230764;
			
			// aapt resource value: 0x7f08002b
			public const int login_btn_login = 2131230763;
			
			// aapt resource value: 0x7f08002e
			public const int login_btn_signup = 2131230766;
			
			// aapt resource value: 0x7f080029
			public const int login_email = 2131230761;
			
			// aapt resource value: 0x7f08002d
			public const int login_layout_or = 2131230765;
			
			// aapt resource value: 0x7f08002a
			public const int login_password = 2131230762;
			
			// aapt resource value: 0x7f08003c
			public const int new_password = 2131230780;
			
			// aapt resource value: 0x7f08004a
			public const int not_remember_button = 2131230794;
			
			// aapt resource value: 0x7f08002f
			public const int offline_button = 2131230767;
			
			// aapt resource value: 0x7f080000
			public const int parent = 2131230720;
			
			// aapt resource value: 0x7f080038
			public const int property_button = 2131230776;
			
			// aapt resource value: 0x7f080049
			public const int remember_button = 2131230793;
			
			// aapt resource value: 0x7f080036
			public const int shop = 2131230774;
			
			// aapt resource value: 0x7f08003e
			public const int sideCardButton = 2131230782;
			
			// aapt resource value: 0x7f080044
			public const int signup_btn_forgot_password = 2131230788;
			
			// aapt resource value: 0x7f080046
			public const int signup_btn_login = 2131230790;
			
			// aapt resource value: 0x7f080043
			public const int signup_btn_register = 2131230787;
			
			// aapt resource value: 0x7f080040
			public const int signup_email = 2131230784;
			
			// aapt resource value: 0x7f08003f
			public const int signup_input_email = 2131230783;
			
			// aapt resource value: 0x7f080041
			public const int signup_input_password = 2131230785;
			
			// aapt resource value: 0x7f080045
			public const int signup_layout_or = 2131230789;
			
			// aapt resource value: 0x7f080042
			public const int signup_password = 2131230786;
			
			// aapt resource value: 0x7f080047
			public const int teachingImageView = 2131230791;
			
			// aapt resource value: 0x7f080034
			public const int teaching_button = 2131230772;
			
			// aapt resource value: 0x7f08000f
			public const int title = 2131230735;
			
			// aapt resource value: 0x7f080019
			public const int title_deck = 2131230745;
			
			// aapt resource value: 0x7f08001d
			public const int title_deck_user = 2131230749;
			
			// aapt resource value: 0x7f080011
			public const int title_false = 2131230737;
			
			// aapt resource value: 0x7f08003b
			public const int title_new_password = 2131230779;
			
			// aapt resource value: 0x7f080015
			public const int translate = 2131230741;
			
			// aapt resource value: 0x7f08000c
			public const int translateArchiveRextView = 2131230732;
			
			// aapt resource value: 0x7f080048
			public const int translate_button = 2131230792;
			
			// aapt resource value: 0x7f080007
			public const int translate_card = 2131230727;
			
			// aapt resource value: 0x7f080014
			public const int word = 2131230740;
			
			// aapt resource value: 0x7f08000b
			public const int wordArchivetextView = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int word_card = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int add_card_admin = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int add_card_user = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int archive_cards = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int archive_decks = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int cards_deck = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int code = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int code_false = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Custom_layout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int decks = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int decks_shop = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int dialog_add_cards_admin = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int dialog_add_deck_admin = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int dialog_add_deck_user = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int edit_delete_item = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int forgot_password = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Main = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int main_menu_admin = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int mian_user = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int new_password = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int property_user = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int sign_up = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int teaching = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int teacjing_decks = 2130903062;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int deck_admin_actionbar = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int main = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dialog_cancel = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int dialog_ok = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_Custom1 = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ConstraintLayout_Layout = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003};
			
			// aapt resource value: 0
			public const int ConstraintLayout_Layout_android_orientation = 0;
			
			// aapt resource value: 1
			public const int ConstraintLayout_Layout_layout_constraintBaseline_creator = 1;
			
			// aapt resource value: 2
			public const int ConstraintLayout_Layout_layout_constraintBaseline_toBaselineOf = 2;
			
			// aapt resource value: 3
			public const int ConstraintLayout_Layout_layout_constraintBottom_creator = 3;
			
			// aapt resource value: 4
			public const int ConstraintLayout_Layout_layout_constraintBottom_toBottomOf = 4;
			
			// aapt resource value: 5
			public const int ConstraintLayout_Layout_layout_constraintBottom_toTopOf = 5;
			
			// aapt resource value: 6
			public const int ConstraintLayout_Layout_layout_constraintDimensionRatio = 6;
			
			// aapt resource value: 7
			public const int ConstraintLayout_Layout_layout_constraintEnd_toEndOf = 7;
			
			// aapt resource value: 8
			public const int ConstraintLayout_Layout_layout_constraintEnd_toStartOf = 8;
			
			// aapt resource value: 9
			public const int ConstraintLayout_Layout_layout_constraintGuide_begin = 9;
			
			// aapt resource value: 10
			public const int ConstraintLayout_Layout_layout_constraintGuide_end = 10;
			
			// aapt resource value: 11
			public const int ConstraintLayout_Layout_layout_constraintGuide_percent = 11;
			
			// aapt resource value: 12
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_bias = 12;
			
			// aapt resource value: 13
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_chainPacked = 13;
			
			// aapt resource value: 14
			public const int ConstraintLayout_Layout_layout_constraintHorizontal_weight = 14;
			
			// aapt resource value: 15
			public const int ConstraintLayout_Layout_layout_constraintLeft_creator = 15;
			
			// aapt resource value: 16
			public const int ConstraintLayout_Layout_layout_constraintLeft_toLeftOf = 16;
			
			// aapt resource value: 17
			public const int ConstraintLayout_Layout_layout_constraintLeft_toRightOf = 17;
			
			// aapt resource value: 18
			public const int ConstraintLayout_Layout_layout_constraintRight_creator = 18;
			
			// aapt resource value: 19
			public const int ConstraintLayout_Layout_layout_constraintRight_toLeftOf = 19;
			
			// aapt resource value: 20
			public const int ConstraintLayout_Layout_layout_constraintRight_toRightOf = 20;
			
			// aapt resource value: 21
			public const int ConstraintLayout_Layout_layout_constraintStart_toEndOf = 21;
			
			// aapt resource value: 22
			public const int ConstraintLayout_Layout_layout_constraintStart_toStartOf = 22;
			
			// aapt resource value: 23
			public const int ConstraintLayout_Layout_layout_constraintTop_creator = 23;
			
			// aapt resource value: 24
			public const int ConstraintLayout_Layout_layout_constraintTop_toBottomOf = 24;
			
			// aapt resource value: 25
			public const int ConstraintLayout_Layout_layout_constraintTop_toTopOf = 25;
			
			// aapt resource value: 26
			public const int ConstraintLayout_Layout_layout_constraintVertical_bias = 26;
			
			// aapt resource value: 27
			public const int ConstraintLayout_Layout_layout_constraintVertical_chainPacked = 27;
			
			// aapt resource value: 28
			public const int ConstraintLayout_Layout_layout_constraintVertical_weight = 28;
			
			// aapt resource value: 29
			public const int ConstraintLayout_Layout_layout_editor_absoluteX = 29;
			
			// aapt resource value: 30
			public const int ConstraintLayout_Layout_layout_editor_absoluteY = 30;
			
			// aapt resource value: 31
			public const int ConstraintLayout_Layout_layout_goneMarginBottom = 31;
			
			// aapt resource value: 32
			public const int ConstraintLayout_Layout_layout_goneMarginEnd = 32;
			
			// aapt resource value: 33
			public const int ConstraintLayout_Layout_layout_goneMarginLeft = 33;
			
			// aapt resource value: 34
			public const int ConstraintLayout_Layout_layout_goneMarginRight = 34;
			
			// aapt resource value: 35
			public const int ConstraintLayout_Layout_layout_goneMarginStart = 35;
			
			// aapt resource value: 36
			public const int ConstraintLayout_Layout_layout_goneMarginTop = 36;
			
			public static int[] ConstraintSet = new int[] {
					16842948,
					16842960,
					16842972,
					16842996,
					16842997,
					16842999,
					16843000,
					16843001,
					16843002,
					16843701,
					16843702,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003};
			
			// aapt resource value: 1
			public const int ConstraintSet_android_id = 1;
			
			// aapt resource value: 4
			public const int ConstraintSet_android_layout_height = 4;
			
			// aapt resource value: 8
			public const int ConstraintSet_android_layout_marginBottom = 8;
			
			// aapt resource value: 10
			public const int ConstraintSet_android_layout_marginEnd = 10;
			
			// aapt resource value: 5
			public const int ConstraintSet_android_layout_marginLeft = 5;
			
			// aapt resource value: 7
			public const int ConstraintSet_android_layout_marginRight = 7;
			
			// aapt resource value: 9
			public const int ConstraintSet_android_layout_marginStart = 9;
			
			// aapt resource value: 6
			public const int ConstraintSet_android_layout_marginTop = 6;
			
			// aapt resource value: 3
			public const int ConstraintSet_android_layout_width = 3;
			
			// aapt resource value: 0
			public const int ConstraintSet_android_orientation = 0;
			
			// aapt resource value: 2
			public const int ConstraintSet_android_visibility = 2;
			
			// aapt resource value: 11
			public const int ConstraintSet_layout_constraintBaseline_creator = 11;
			
			// aapt resource value: 12
			public const int ConstraintSet_layout_constraintBaseline_toBaselineOf = 12;
			
			// aapt resource value: 13
			public const int ConstraintSet_layout_constraintBottom_creator = 13;
			
			// aapt resource value: 14
			public const int ConstraintSet_layout_constraintBottom_toBottomOf = 14;
			
			// aapt resource value: 15
			public const int ConstraintSet_layout_constraintBottom_toTopOf = 15;
			
			// aapt resource value: 16
			public const int ConstraintSet_layout_constraintDimensionRatio = 16;
			
			// aapt resource value: 17
			public const int ConstraintSet_layout_constraintEnd_toEndOf = 17;
			
			// aapt resource value: 18
			public const int ConstraintSet_layout_constraintEnd_toStartOf = 18;
			
			// aapt resource value: 19
			public const int ConstraintSet_layout_constraintGuide_begin = 19;
			
			// aapt resource value: 20
			public const int ConstraintSet_layout_constraintGuide_end = 20;
			
			// aapt resource value: 21
			public const int ConstraintSet_layout_constraintGuide_percent = 21;
			
			// aapt resource value: 22
			public const int ConstraintSet_layout_constraintHorizontal_bias = 22;
			
			// aapt resource value: 23
			public const int ConstraintSet_layout_constraintHorizontal_chainPacked = 23;
			
			// aapt resource value: 24
			public const int ConstraintSet_layout_constraintHorizontal_weight = 24;
			
			// aapt resource value: 25
			public const int ConstraintSet_layout_constraintLeft_creator = 25;
			
			// aapt resource value: 26
			public const int ConstraintSet_layout_constraintLeft_toLeftOf = 26;
			
			// aapt resource value: 27
			public const int ConstraintSet_layout_constraintLeft_toRightOf = 27;
			
			// aapt resource value: 28
			public const int ConstraintSet_layout_constraintRight_creator = 28;
			
			// aapt resource value: 29
			public const int ConstraintSet_layout_constraintRight_toLeftOf = 29;
			
			// aapt resource value: 30
			public const int ConstraintSet_layout_constraintRight_toRightOf = 30;
			
			// aapt resource value: 31
			public const int ConstraintSet_layout_constraintStart_toEndOf = 31;
			
			// aapt resource value: 32
			public const int ConstraintSet_layout_constraintStart_toStartOf = 32;
			
			// aapt resource value: 33
			public const int ConstraintSet_layout_constraintTop_creator = 33;
			
			// aapt resource value: 34
			public const int ConstraintSet_layout_constraintTop_toBottomOf = 34;
			
			// aapt resource value: 35
			public const int ConstraintSet_layout_constraintTop_toTopOf = 35;
			
			// aapt resource value: 36
			public const int ConstraintSet_layout_constraintVertical_bias = 36;
			
			// aapt resource value: 37
			public const int ConstraintSet_layout_constraintVertical_chainPacked = 37;
			
			// aapt resource value: 38
			public const int ConstraintSet_layout_constraintVertical_weight = 38;
			
			// aapt resource value: 39
			public const int ConstraintSet_layout_editor_absoluteX = 39;
			
			// aapt resource value: 40
			public const int ConstraintSet_layout_editor_absoluteY = 40;
			
			// aapt resource value: 41
			public const int ConstraintSet_layout_goneMarginBottom = 41;
			
			// aapt resource value: 42
			public const int ConstraintSet_layout_goneMarginEnd = 42;
			
			// aapt resource value: 43
			public const int ConstraintSet_layout_goneMarginLeft = 43;
			
			// aapt resource value: 44
			public const int ConstraintSet_layout_goneMarginRight = 44;
			
			// aapt resource value: 45
			public const int ConstraintSet_layout_goneMarginStart = 45;
			
			// aapt resource value: 46
			public const int ConstraintSet_layout_goneMarginTop = 46;
			
			public static int[] LinearConstraintLayout = new int[] {
					16842948};
			
			// aapt resource value: 0
			public const int LinearConstraintLayout_android_orientation = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
